version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: support_bot_postgres
    environment:
      POSTGRES_DB: support_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "6432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: always
    networks:
      - support_bot_network

  redis:
    image: redis:7-alpine
    container_name: support_bot_redis
    ports:
      - "6389:6379"
    restart: always
    networks:
      - support_bot_network

volumes:
  postgres_data:

networks:
  support_bot_network:
    driver: bridge
